### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by shadowdree** [MerengueRover/2003page.ga#95]
Hi., I have some issues doing a music player can someone help me? Thoinks

**Comment by forkiesassds** [comment]
Can you push your changes to the repo?

**Comment by EricZhang456** [comment]
Dang why can't you copy and paste

**Comment by forkiesassds** [comment]
Also we can't help you without your code.

**Comment by PF94** [comment]
Unassigning myself from this issue. I have better things to do than copy and pasting code.

**Comment by shadowdree** [comment]
I am sorry but I accidently destroyed my code
